# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Copiamos package.json y package-lock.json (o yarn.lock si existe)
COPY package*.json yarn*.lock ./

# Instalamos las dependencias
RUN npm install

# Cambiamos la propiedad de /app al usuario node
RUN chown -R node:node /app

# Cambiamos al usuario node
USER node

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]