services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: web-front
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    env_file:
      - ./.env

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ns_santarita
      MYSQL_USER: ns_santarita
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: